version: "3.9"

services:
  sqlserver:
    build: ./docker/sqlserver
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "${DB_PASSWORD:-HvQfOKgVcNMM0G3MX755qr9n7!}"
      DB_PASSWORD: "${DB_PASSWORD:-HvQfOKgVcNMM0G3MX755qr9n7!}"
      DB_NAME: "${DB_NAME:-sollic}"
      DB_USER: "${DB_USER:-sollic}"
    ports:
      - "${DB_PORT:-1433}:1433"
    volumes:
      - database-data:/var/opt/mssql

volumes:
  database-data:
    driver: local