version: "3.9"

services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "${DB_PORT:-1433}:1433"
    environment:
      SA_PASSWORD: "${DB_PASSWORD:-HvQfOKgVcNMM0G3MX755qr9n7!}"
      ACCEPT_EULA: "Y"
    volumes:
      - database-data:/var/opt/mssql

volumes:
  database-data:
    driver: local
